#A script to fit GAMs to examine associations between R1 and EEG aperiodic activity 
library(tidyr)
library(mgcv)
library(gratia)
library(tidyverse)
library(dplyr)

############################################################################################################
#### Prepare Data and Functions ####

#EEG electrode atlas cortical areas list
electrodes <- c("vlpfc", "dlpfc", "spfc", "motor")

#Depth-specific (superficial/deep) R1 and fooof measures for final study sample
R1_aperiodicactivity_electrodeatlas <- readRDS("/Volumes/Hera/Projects/corticalmyelin_development/EEG/R1_aperiodicactivity_electrodeatlas.RDS") #generated by /image_processing/EEG_aperiodic/fooof_aperiodicactivity.R
R1_aperiodicactivity_electrodeatlas <- lapply(R1_aperiodicactivity_electrodeatlas, function(depth){
  depth$subject_id <- as.factor(depth$subject_id) #factor for gam modeling
  return(depth)
})

SGIGR1_aperiodicactivity_electrodeatlas <- do.call(rbind, R1_aperiodicactivity_electrodeatlas)
SGIGR1_aperiodicactivity_electrodeatlas$depth <- factor(sub("\\..*$", "", row.names(SGIGR1_aperiodicactivity_electrodeatlas)), levels = c("deep", "superficial"), ordered = T) #ordered factor for interactions

#Gam functions
source("/Volumes/Hera/Projects/corticalmyelin_development/code/corticalmyelin_maturation/gam_models/gam_functions.R")

############################################################################################################
#### Fit GAMs to quantify depth-specific associations between R1 and aperiodic activity ####

R1.aperiodic.maineffect.gams <- function(input.depth.df, aperiodic.measure, output.df.name){
  
  #Run the gam.covariatesmooth.maineffect function to get statistics for a main effect of aperiodic measure on R1 as well as fitted values/smooth estimates describing this relationship
  gam.outputs.regionlist <- lapply(electrodes, function(r){  #list of gam results, list elements are cortical areas
    gam.covariatesmooth.maineffect(input.df = input.depth.df, region = sprintf("%s_R1", r), 
                           smooth_var = "age", smooth_var_knots = 4, smooth_covariate = sprintf("%s_%s", r, aperiodic.measure), smooth_covariate_knots = 3, 
                           linear_covariates = "NA", id_var = "subject_id", random_intercepts = TRUE, set_fx = FALSE)}) 
  
  #Extract and combine gam statistics ouputs
  gam.statistics.df <- lapply(gam.outputs.regionlist, '[[', "gam.statistics" ) #extract this df from each region's list
  gam.statistics.df <- do.call(rbind, gam.statistics.df) #merge them into one 
  
  #Extract and combine fitted values 
  gam.fittedvalues.df <- lapply(gam.outputs.regionlist, '[[', "gam.fittedvalues" ) #extract this df from each region's list
  gam.fittedvalues.df <- lapply(gam.fittedvalues.df, function(output){
      region.name <- sub("_.*", "", names(output)[1]) 
      output$region <- region.name
      names(output)[1] <- aperiodic.measure
      return(output)
  })
  gam.fittedvalues.df <- do.call(rbind, gam.fittedvalues.df) #merge them into one 
  
  #Extract and combine smooth estimates
  gam.smoothestimates.df <- lapply(gam.outputs.regionlist, '[[', "gam.smoothestimates" ) #extract this df from each region's list
  gam.smoothestimates.df <- lapply(gam.smoothestimates.df, function(output){
    region.name <- sub("_.*", "", names(output)[1]) 
    output$region <- region.name
    names(output)[1] <- aperiodic.measure
    return(output)
  })
  gam.smoothestimates.df <- do.call(rbind, gam.smoothestimates.df) #merge them into one 
  
  #Extract and combine derivatives
  gam.derivatives.df <- lapply(gam.outputs.regionlist, '[[', "gam.derivatives" ) #extract this df from each region's list
  gam.derivatives.df <- lapply(gam.derivatives.df, function(output){
    region.name <- sub("_.*", "", names(output)[1]) 
    output$region <- region.name
    names(output)[1] <- aperiodic.measure
    return(output)
  })
  gam.derivatives.df <- do.call(rbind, gam.derivatives.df) #merge them into one 
  
  #Save depth-specific results as an RDS
  gam.outputs.statslist <- list(gam.statistics.df, gam.fittedvalues.df, gam.smoothestimates.df, gam.derivatives.df) #list of gam results, list elements are stats dfs binded across regions
  names(gam.outputs.statslist) <- list("gam.statistics.df", "gam.fittedvalues.df", "gam.smoothestimates.df", "gam.derivatives.df")
  saveRDS(gam.outputs.statslist, sprintf("/Volumes/Hera/Projects/corticalmyelin_development/gam_outputs/eeg_associations/%s", output.df.name))
  
  #Clean up
  gc(gam.outputs.statslist)
}

## Exponent

R1.aperiodic.maineffect.gams(input.depth.df = R1_aperiodicactivity_electrodeatlas$superficial, aperiodic.measure = "exponent", output.df.name = "R1exponent_superficial_maineffect.RDS")
R1.aperiodic.maineffect.gams(input.depth.df = R1_aperiodicactivity_electrodeatlas$deep, aperiodic.measure = "exponent", output.df.name = "R1exponent_deep_maineffect.RDS")

## Offset

R1.aperiodic.maineffect.gams(input.depth.df = R1_aperiodicactivity_electrodeatlas$superficial, aperiodic.measure = "offset", output.df.name = "R1offset_superficial_maineffect.RDS")
R1.aperiodic.maineffect.gams(input.depth.df = R1_aperiodicactivity_electrodeatlas$deep, aperiodic.measure = "offset", output.df.name = "R1offset_deep_maineffect.RDS")


############################################################################################################
#### Fit GAMs to statistically test whether associations between R1 and aperiodic activity differ by depth (depth interactions) ####

R1.aperiodic.interaction.gams <- function(input.depth.df, aperiodic.measure, output.df.name){
  
  #Run the gam.factorsmooth.interaction function to get R1 ~ aperiodic*depth interaction statistics
  
  gam.outputs.regionlist <- lapply(electrodes, function(r){ 
    gam.factorsmooth.interaction(input.df = input.depth.df, region = sprintf("%s_R1", r), 
                                   smooth_var = "age", smooth_var_knots = 4, smooth_covariate = sprintf("%s_%s", r, aperiodic.measure), smooth_covariate_knots = 3, 
                                   int_var = "depth", linear_covariates = "depth", id_var = "subject_id", random_intercepts = TRUE, set_fx = FALSE)}) 
    
    gam.statistics.df <- do.call(rbind, gam.outputs.regionlist) #merge them into one 
    saveRDS(gam.statistics.df, sprintf("/Volumes/Hera/Projects/corticalmyelin_development/gam_outputs/eeg_associations/%s", output.df.name))
}
    
## Exponent

R1.aperiodic.interaction.gams(input.depth.df = SGIGR1_aperiodicactivity_electrodeatlas, aperiodic.measure = "exponent", output.df.name = "R1exponent_depth_interaction.RDS")

  
  
  