---
title: "BrainSmash: Cortical Myeloarchitecture Map Correlation Significance Testing"
author: "Valerie Jill Sydnor"
output: 
  rmdformats::material:
    highlight: monochrome
    lightbox: true
    gallery: true
    css: /Volumes/Hera/Projects/corticalmyelin_development/code/corticalmyelin_maturation/results/custom_css/myelinanatomy.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggseg)
library(ggsegGlasser)
library(readr)
```

# Read in Data

Glasser regions list

```{r}
glasser.regions <- read.csv("/Volumes/Hera/Projects/corticalmyelin_development/Maps/HCPMMP_glasseratlas/glasser360_regionlist.csv")
glasser.snr.exclude <- read.csv("/Volumes/Hera/Projects/corticalmyelin_development/Maps/SNR/glasser_SNR_exclusion.csv")
glasser.frontal <- read.csv("/Volumes/Hera/Projects/corticalmyelin_development/Maps/HCPMMP_glasseratlas/glasser360_regionlist_frontallobe.csv")
```

Myelin map data for correlation significance testing

```{r}
myelin.maps <- read.csv("/Volumes/Hera/Projects/corticalmyelin_development/code/corticalmyelin_maturation/results/R1_corticalmyelin_anatomy/myelin_maps/myelin_maps.csv") # generated by /results/R1_cortical_myeloarchitecture.Rmd
myelin.maps <- left_join(glasser.regions, myelin.maps, by = c("orig_parcelname", "label")) #order in rh -> lh order of full glasser.regions list
```

R1 autocorrelation-preserving surrogates

```{r}
#Hemisphere-specific surrogates generated by brainsmash (n = 500 per hemisphere)
surrogate_maps_rh <- read.csv("/Volumes/Hera/Projects/corticalmyelin_development/Maps/Brainsmash/smash_data/R1.rh.surrogates.txt") %>% t() %>% as.data.frame() #180 rows are RH regions, 500 columns are 500 surrogate maps 
surrogate_maps_lh <-read.csv("/Volumes/Hera/Projects/corticalmyelin_development/Maps/Brainsmash/smash_data/R1.lh.surrogates.txt") %>% t() %>% as.data.frame() #180 rows are LH regions, 500 columns are 500 surrogate maps 

#Reflect data across hemisphere to generate whole-brain surrogate maps
surrogate_maps_rh <- rbind(surrogate_maps_rh, surrogate_maps_rh)
surrogate_maps_lh <- rbind(surrogate_maps_lh, surrogate_maps_lh)

#NA out low SNR parcels to exclude from null correlation tests
surrogate_maps_rh$orig_parcelname <- glasser.regions$orig_parcelname
surrogate_maps_rh <- surrogate_maps_rh[!(surrogate_maps_rh$orig_parcelname %in% glasser.snr.exclude$orig_parcelname),]
surrogate_maps_rh <- left_join(glasser.regions, surrogate_maps_rh, by = "orig_parcelname")

surrogate_maps_lh$orig_parcelname <- glasser.regions$orig_parcelname
surrogate_maps_lh <- surrogate_maps_lh[!(surrogate_maps_lh$orig_parcelname %in% glasser.snr.exclude$orig_parcelname),]
surrogate_maps_lh <- left_join(glasser.regions, surrogate_maps_lh, by = "orig_parcelname")

surrogate_maps <- merge(surrogate_maps_rh, surrogate_maps_lh, by = c("label", "orig_parcelname"), sort = F) #1000 nulls!
colnames(surrogate_maps)[3:1002] <-  sprintf("map%s",seq(from = 1, to = 1000)) 
```

# Visualize Example Brainmash Autocorrelation-Preserving Nulls

```{r, warning = F, message = F}
myelin.colorbar <- c("#edf6ff", "#c2d4ed", "#809dc4", "#345c91", "#0e4669")

for(map in c("map1", "map100", "map200", "map300", "map400", "map500", "map600", "map700", "map800", "map900", "map100")){
  null.map <- surrogate_maps %>% filter(label != "lh_L_10pp") %>% select(label, map)
  colnames(null.map)<- c("label", "nullmap")
  SA.nullmap.plot <- ggseg(.data = null.map, atlas = "glasser", mapping = aes(fill = nullmap), colour=I("gray50"), size=I(.06)) +
  scale_fill_gradientn(colors = myelin.colorbar, na.value = "gray75") + theme(legend.position = "none")
  print(SA.nullmap.plot)
}
```

# Compute Brainsmash Null-Based Correlation Significance

```{r}
#Get all the single empirical and 1000 null maps
surrogate_maps.myelin <- left_join(surrogate_maps, myelin.maps, by = c("orig_parcelname", "label")) #ensure regional ordering matches across all null and empirical maps to be correlated
surrogate_maps <- surrogate_maps.myelin %>% select(contains("map")) #just the 1000 null maps
R1 <- surrogate_maps.myelin %>% select(mean.R1)
myelin.map.PC1 <- surrogate_maps.myelin %>% select(PC1)
```

```{r}
#Function to compute the brainsmash-based permutation p-value (pSMASH!) given an empirical correlation between R1-map and the SA-preserving null R1 maps #super smash bros
brainsmash.results <- function(empirical.map){
  empirical.cor <- cor(empirical.map, R1, method = c("spearman"), use = "complete.obs") #true correlation 
  null.cors <- cor(empirical.map, surrogate_maps, method = c("spearman"), use = "complete.obs") #correlation with brainsmash based surrogates 
  mean.nullcor <- mean(abs(null.cors))*-1 #null correlation direction is arbitrary make all corrs negative so we are comparing correlation strength between negative rs
 
  brainsmash.p <- sum(null.cors < empirical.cor[1])/1000

  smash.results <- list(empirical.cor[1], mean.nullcor, brainsmash.p)
  names(smash.results) <- list("empirical.cor", "average.null.cor", "brainsmash.pvalue")
  return(smash.results)
}
```

## R1 and Myelin Map PC1

```{r}
brainsmash.results(empirical.map = myelin.map.PC1)
```


